### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by Jparrgam** [rekabhq/background_locator#159]
hi bro @mehdok  I have the following error in my application could you help me

`Caused by java.lang.IllegalStateException: FlutterCallbackInformati…formation(callbackHandle) must not be null
       at ..backgroundlocator.LocatorService.startLocatorService(LocatorService.kt:90)
       at ...backgroundlocator.LocatorService.onCreate(LocatorService.kt:71)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3749)
       at android.app.ActivityThread.access$1400(ActivityThread.java:213)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)`

I am starting the background locator as follows

`BackgroundLocator.registerLocationUpdate(
            _locationUpdate,
            initCallback: _initCallback,
            disposeCallback: _disposeCallback,
            initDataCallback: data,
            settings: LocationSettings(
                notificationChannelName: '_trackingService',
                notificationTitle: lang.notificationTitleDriverMode,
                notificationMsg: 'test',
                wakeLockTime: 20,
                autoStop: false,
                distanceFilter: 0,
                interval: 10),
          );
        });`

**Comment by mehdok** [comment]
Hi @Jparrgam 
Thank you for opening an issue.

Did you declare your callback function as a global function? the callback should be global or static to prevent this error;

**Comment by PaulBout1** [comment]
Hi, I had the same issue. 
`background_locator` failed while initializing because I didn't checked if plugins I used was already registerer before registration. 
So check your Android `Application.kt`

replace 
```
override fun registerWith(registry: PluginRegistry?) {
        io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
        io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }```
by

```
override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin(SharedPreferencesPlugin::class.qualifiedName)) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor(SharedPreferencesPlugin::class.qualifiedName))
        }
        if (!registry!!.hasPlugin(FirebaseMessagingPlugin::class.qualifiedName)) {
            FirebaseMessagingPlugin.registerWith(registry!!.registrarFor(FirebaseMessagingPlugin::class.qualifiedName))
        }
    }
```
